"""Two-pass visual food matching with deterministic database nutrient scaling."""

import json
import time

from shared.config import OPENROUTER_MAX_OUTPUT_TOKENS, openrouter_reasoning

from .base import FoodAnalysisResult, FoodItem, encode_image_to_base64, get_image_media_type
from .nutrition_db import NutritionDB, NutrientInfo
from .vlm_analyzer import VLMAnalyzerSingleShot


class GroundedVLMAnalyzer(VLMAnalyzerSingleShot):
    method_name = "vlm_db_grounded"

    INVENTORY_PROMPT = """Inspect the meal image. Identify separate edible components,
their preparation (raw/cooked, fried/boiled, skin, sauces) and approximate edible grams.
Use English food names and give up to three alternative database search names per item.
For mixed dishes, choose either a complete dish or non-overlapping components, never both.
Separate visible added sauces/oils only when they are not included in the prepared food.
Do not invent hidden ingredients. Describe visible scale cues, occlusions and uncertainty.
Plate size is unknown: common plate dimensions are assumptions, not measurements.
Do not claim measured depth, volume or weight from this RGB image.
Return ONLY JSON: {"visual_assumptions": "...", "items": [
{"name": "steamed white rice", "preparation": "cooked", "quantity_grams": 120,
 "search_names": ["white rice", "rice"], "portion_description": "small mound"}]}.
Do not estimate nutrients yet."""

    MATCH_PROMPT = """Review the same image and the inventory with candidate nutrition
entries below. For EACH inventory item, choose an exact candidate name as db_name only
when it reasonably matches the food AND preparation. Similar spelling alone is insufficient.
Reject incompatible raw/cooked, dry/hydrated, fried/plain or composite/component matches.
Some catalog entries have incomplete preparation descriptions: use their nutrient profiles
to assess compatibility, and state assumptions. Reconsider edible grams using the image.
Avoid double counting mixed dishes, sauces or cooking fat already included in an entry.
Do not force small garnishes to standard serving sizes. No serving-size clamping is applied.
When NO candidate fits, set db_name to null and provide fallback_per_100g using your
nutrition knowledge; explain the missing match. This is recorded as model fallback.
For matched items, nutrients will be calculated in Python, not generated by you.
Return ONLY JSON: {"items": [{"item_id": 0, "db_name": "white rice",
 "quantity_grams": 120, "portion_description": "...", "match_reason": "..."}]}.
For unmatched items include fallback_per_100g with calories, protein_g, carbs_g, fat_g.
Return each item_id exactly once. Do not output total meal nutrients.

Inventory and candidate entries (nutrients per 100 edible grams):
"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.nutrition_db = NutritionDB()

    def _image_call(self, prompt, image_url):
        response = self._get_client().chat.completions.create(
            model=self.model,
            messages=[{"role": "user", "content": [
                {"type": "text", "text": prompt},
                {"type": "image_url", "image_url": {"url": image_url}},
            ]}],
            max_tokens=OPENROUTER_MAX_OUTPUT_TOKENS,
            extra_body=openrouter_reasoning(self.reasoning_effort),
            temperature=0.1,
        )
        return response.choices[0].message.content.strip()

    def analyze(self, image_path: str) -> FoodAnalysisResult:
        started = time.perf_counter()
        result = FoodAnalysisResult(method=self.method_name)
        trace = {}
        try:
            if not self.api_key:
                raise ValueError("OPENROUTER_API_KEY not set.")
            image_url = f"data:{get_image_media_type(image_path)};base64,{encode_image_to_base64(image_path)}"
            trace["inventory_response"] = self._image_call(self.INVENTORY_PROMPT, image_url)
            inventory = self._parse_json(trace["inventory_response"], dict)
            if not inventory or not isinstance(inventory.get("items"), list) or not inventory["items"]:
                raise ValueError("Could not parse food inventory")
            candidates = []
            for index, item in enumerate(inventory["items"]):
                if not isinstance(item, dict) or not isinstance(item.get("name"), str) or not item["name"].strip():
                    raise ValueError("Inventory items must have food names")
                aliases = item.get("search_names", [])
                if not isinstance(aliases, list):
                    raise ValueError("search_names must be a list")
                candidates.append({"item_id": index, "inventory": item,
                                   "candidates": self.nutrition_db.search_candidates([item["name"], *aliases])})
            trace["candidates"] = candidates
            payload = {"visual_assumptions": inventory.get("visual_assumptions", ""), "items": candidates}
            trace["matching_response"] = self._image_call(self.MATCH_PROMPT + json.dumps(payload), image_url)
            matched = self._parse_json(trace["matching_response"], dict)
            if not matched or not isinstance(matched.get("items"), list):
                raise ValueError("Could not parse database matching")
            predictions = matched["items"]
            ids = [item.get("item_id") if isinstance(item, dict) else None for item in predictions]
            if any(type(index) is not int for index in ids) or sorted(ids) != list(range(len(candidates))):
                raise ValueError("Matching must return every inventory item_id exactly once")
            items = []
            for prediction in predictions:
                entry = candidates[prediction["item_id"]]
                name = entry["inventory"]["name"]
                db_name = prediction.get("db_name")
                if db_name is None:
                    nutrients = NutrientInfo(**prediction["fallback_per_100g"])
                    source = "model fallback (no compatible database entry)"
                else:
                    allowed = [candidate["name"] for candidate in entry["candidates"]]
                    if db_name not in allowed:
                        raise ValueError(f"Database entry not in retrieved candidates: {db_name}")
                    nutrients = self.nutrition_db.db[db_name]
                    source = f"database: {db_name}"
                grams = float(prediction["quantity_grams"])
                description = f"{prediction.get('portion_description', '')}; {source}; {prediction.get('match_reason', '')}"
                items.append(FoodItem(name=name, quantity_grams=grams, portion_description=description,
                                      **nutrients.scaled(grams)))
            result.food_items = items
            result.compute_totals()
        except Exception as exc:
            result.error = str(exc)
        result.raw_response = json.dumps(trace, ensure_ascii=False)
        result.elapsed_seconds = time.perf_counter() - started
        return result
