"""RADAR-style adversarial detector training.

Implements the defender side of the arms race: retrain a RoBERTa-based
detector on the latest attacker outputs so it can detect the new
attack distribution.

Reference: Hu, Chen, Ho. RADAR (NeurIPS 2023, arXiv:2307.03838)
"""

from __future__ import annotations

import logging
import os
from typing import Dict, List, Optional

import numpy as np
import torch

logger = logging.getLogger(__name__)


class RADARDefender:
    """RADAR-style adversarial detector that retrains on attacker outputs.

    Each round:
    1. Receive fresh AI-generated texts from the current attacker.
    2. Combine with human reference texts.
    3. Fine-tune a RoBERTa classifier on this data.
    4. Export the updated detector for the next attacker round.
    """

    def __init__(
        self,
        model_name: str = "roberta-base",
        output_dir: str = "results/radar_defender",
        retrain_samples: int = 2000,
        epochs: int = 3,
        lr: float = 2e-5,
        max_length: int = 512,
    ):
        self.model_name = model_name
        self.output_dir = output_dir
        self.retrain_samples = retrain_samples
        self.epochs = epochs
        self.lr = lr
        self.max_length = max_length
        self.model = None
        self.tokenizer = None
        self._round = 0

    def setup(self):
        """Initialize the detector model."""
        from transformers import AutoModelForSequenceClassification, AutoTokenizer

        self.tokenizer = AutoTokenizer.from_pretrained(self.model_name)
        self.model = AutoModelForSequenceClassification.from_pretrained(
            self.model_name,
            num_labels=2,
        )
        if torch.cuda.is_available():
            self.model = self.model.cuda()

        os.makedirs(self.output_dir, exist_ok=True)
        logger.info("RADAR defender initialized with %s", self.model_name)

    def retrain(
        self,
        ai_texts: List[str],
        human_texts: List[str],
    ) -> Dict[str, float]:
        """Retrain the detector on new attacker outputs + human texts.

        Args:
            ai_texts: Texts generated by the current attacker.
            human_texts: Human reference texts.

        Returns:
            Dict with training metrics (accuracy, auroc, loss).
        """
        self._round += 1
        logger.info("RADAR defender retrain — round %d", self._round)

        from transformers import Trainer, TrainingArguments
        from datasets import Dataset

        # Balance classes
        n = min(len(ai_texts), len(human_texts), self.retrain_samples // 2)
        texts = ai_texts[:n] + human_texts[:n]
        labels = [1] * n + [0] * n  # 1 = AI, 0 = human

        # Shuffle
        indices = np.random.permutation(len(texts))
        texts = [texts[i] for i in indices]
        labels = [labels[i] for i in indices]

        # Split train/val
        split = int(0.8 * len(texts))
        train_texts, val_texts = texts[:split], texts[split:]
        train_labels, val_labels = labels[:split], labels[split:]

        # Tokenize
        def tokenize_fn(examples):
            return self.tokenizer(
                examples["text"],
                truncation=True,
                max_length=self.max_length,
                padding="max_length",
            )

        train_ds = Dataset.from_dict({"text": train_texts, "label": train_labels})
        val_ds = Dataset.from_dict({"text": val_texts, "label": val_labels})
        train_ds = train_ds.map(tokenize_fn, batched=True)
        val_ds = val_ds.map(tokenize_fn, batched=True)
        train_ds.set_format("torch", columns=["input_ids", "attention_mask", "label"])
        val_ds.set_format("torch", columns=["input_ids", "attention_mask", "label"])

        # Train
        training_args = TrainingArguments(
            output_dir=os.path.join(self.output_dir, f"round_{self._round}"),
            num_train_epochs=self.epochs,
            per_device_train_batch_size=8,
            per_device_eval_batch_size=16,
            learning_rate=self.lr,
            eval_strategy="epoch",
            save_strategy="epoch",
            load_best_model_at_end=True,
            metric_for_best_model="eval_loss",
            logging_steps=50,
            seed=42,
            report_to="none",
        )

        from sklearn.metrics import accuracy_score, roc_auc_score

        def compute_metrics(eval_pred):
            logits, labels_arr = eval_pred
            preds = np.argmax(logits, axis=-1)
            probs = torch.softmax(torch.tensor(logits), dim=-1).numpy()[:, 1]
            acc = accuracy_score(labels_arr, preds)
            try:
                auroc = roc_auc_score(labels_arr, probs)
            except ValueError:
                auroc = 0.5
            return {"accuracy": acc, "auroc": auroc}

        trainer = Trainer(
            model=self.model,
            args=training_args,
            train_dataset=train_ds,
            eval_dataset=val_ds,
            compute_metrics=compute_metrics,
        )

        train_result = trainer.train()
        eval_result = trainer.evaluate()

        metrics = {
            "round": self._round,
            "train_loss": train_result.training_loss,
            "accuracy": eval_result.get("eval_accuracy", 0),
            "auroc": eval_result.get("eval_auroc", 0.5),
            "eval_loss": eval_result.get("eval_loss", 0),
            "train_samples": len(train_ds),
            "val_samples": len(val_ds),
        }

        logger.info(
            "Defender round %d: accuracy=%.3f, auroc=%.3f",
            self._round, metrics["accuracy"], metrics["auroc"],
        )

        return metrics

    def predict(self, text: str) -> float:
        """Predict AI probability for a single text.

        Returns:
            Float in [0, 1] — probability that text is AI-generated.
        """
        if self.model is None:
            return 0.5

        device = next(self.model.parameters()).device
        tokens = self.tokenizer(
            text,
            return_tensors="pt",
            truncation=True,
            max_length=self.max_length,
            padding=True,
        ).to(device)

        self.model.eval()
        with torch.no_grad():
            logits = self.model(**tokens).logits
            probs = torch.softmax(logits, dim=-1).cpu().numpy()[0]

        return float(probs[1])  # probability of class 1 = AI

    def predict_batch(self, texts: List[str]) -> List[float]:
        """Predict AI probability for a batch of texts."""
        return [self.predict(t) for t in texts]
